import test from "node:test";
import assert from "node:assert/strict";
import Driver from "../models/Driver.js";
import app from "../app.js";

test("only admin can review a pending driver", async () => {
  const oldUsername = process.env.ADMIN_USERNAME;
  const oldPassword = process.env.ADMIN_PASSWORD;
  const oldSecret = process.env.AccessTokenSecret;
  const oldAutofill = process.env.ENABLE_ADMIN_AUTOFILL;
  const oldDemos = process.env.ENABLE_DEMO_ACCOUNTS;
  const oldNodeEnv = process.env.NODE_ENV;
  const originalFind = Driver.find;
  const originalCount = Driver.countDocuments;
  const originalFindById = Driver.findById;
  const originalUpdate = Driver.findOneAndUpdate;
  process.env.ADMIN_USERNAME = "test_admin";
  process.env.ADMIN_PASSWORD = "test-admin-password-123456";
  process.env.AccessTokenSecret = "test-access-secret-longer-than-thirty-two-bytes";
  process.env.ENABLE_ADMIN_AUTOFILL = "true";
  process.env.ENABLE_DEMO_ACCOUNTS = "true";
  process.env.NODE_ENV = "test";
  app.locals.databaseReady = true;
  const id = "507f1f77bcf86cd799439022";
  const driver = { id, name: "Jashim", username: "demo_jashim", verificationStatus: "pending", availability: "online", verificationHistory: [] };
  let lastFilter;
  Driver.find = (filter) => { lastFilter = filter; return { sort: () => ({ skip: () => ({ limit: async () => filter.verificationStatus?.$in && !filter.verificationStatus.$in.includes(driver.verificationStatus) ? [] : [driver] }) }) }; };
  Driver.countDocuments = async () => 1;
  Driver.findById = async (candidate) => candidate === id ? driver : null;
  Driver.findOneAndUpdate = async (filter, update) => {
    if (filter._id !== id || !filter.verificationStatus.$in.includes(driver.verificationStatus)) return null;
    Object.assign(driver, update.$set);
    driver.verificationHistory.push(update.$push.verificationHistory);
    return driver;
  };
  const server = app.listen(0, "127.0.0.1");
  await new Promise((resolve) => server.once("listening", resolve));
  const base = `http://127.0.0.1:${server.address().port}/api/admin`;
  try {
    const autofill = await fetch(`${base}/local-autofill`);
    assert.equal(autofill.status, 200);
    assert.deepEqual((await autofill.json()).data, { username: "test_admin", password: "test-admin-password-123456" });
    process.env.NODE_ENV = "production";
    assert.equal((await fetch(`${base}/local-autofill`)).status, 404);
    process.env.NODE_ENV = "test";
    const anonymous = await fetch(`${base}/drivers/${id}/verification`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "approved" }) });
    assert.equal(anonymous.status, 401);
    assert.equal((await fetch(`${base}/drivers/${id}`)).status, 401);
    const wrong = await fetch(`${base}/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: "test_admin", password: "wrong" }) });
    assert.equal(wrong.status, 401);
    const login = await fetch(`${base}/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: "test_admin", password: "test-admin-password-123456" }) });
    assert.equal(login.status, 200);
    const cookie = login.headers.getSetCookie().find((value) => value.startsWith("tesla_pool_admin_session=")).split(";")[0];
    const details = await fetch(`${base}/drivers/${id}`, { headers: { Cookie: cookie } });
    assert.equal(details.status, 200);
    assert.equal((await details.json()).data.driver.name, "Jashim");
    const pending = await fetch(`${base}/drivers/pending`, { headers: { Cookie: cookie } });
    assert.equal((await pending.json()).data.drivers.length, 1);
    const beforeApproval = await fetch(`${base}/drivers`, { headers: { Cookie: cookie } });
    assert.equal((await beforeApproval.json()).data.drivers.length, 1);
    const approved = await fetch(`${base}/drivers/${id}/verification`, { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: cookie }, body: JSON.stringify({ status: "approved" }) });
    assert.equal(approved.status, 200);
    assert.equal(driver.verificationStatus, "approved");
    const filtered = await fetch(`${base}/drivers?field=username&q=demo_jashim&seats=2`, { headers: { Cookie: cookie } });
    assert.equal(filtered.status, 200);
    assert.equal((await filtered.json()).data.drivers.length, 1);
    assert.equal(lastFilter.verificationStatus, undefined);
    assert.equal(lastFilter.passengerSeats, 2);
    assert.equal(lastFilter.username.test("demo_jashim"), true);
    const badSeats = await fetch(`${base}/drivers?seats=5`, { headers: { Cookie: cookie } });
    assert.equal(badSeats.status, 400);
    const repeat = await fetch(`${base}/drivers/${id}/verification`, { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: cookie }, body: JSON.stringify({ status: "rejected" }) });
    assert.equal(repeat.status, 409);
    const revoked = await fetch(`${base}/drivers/${id}/verification`, { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: cookie }, body: JSON.stringify({ status: "unverified" }) });
    assert.equal(revoked.status, 200);
    assert.equal(driver.verificationStatus, "unverified");
    assert.equal(driver.availability, "offline");
    assert.equal(driver.verificationHistory.length, 2);
    const reapproved = await fetch(`${base}/drivers/${id}/verification`, { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: cookie }, body: JSON.stringify({ status: "approved" }) });
    assert.equal(reapproved.status, 200);
  } finally {
    Driver.find = originalFind;
    Driver.countDocuments = originalCount;
    Driver.findById = originalFindById;
    Driver.findOneAndUpdate = originalUpdate;
    if (oldUsername === undefined) delete process.env.ADMIN_USERNAME; else process.env.ADMIN_USERNAME = oldUsername;
    if (oldPassword === undefined) delete process.env.ADMIN_PASSWORD; else process.env.ADMIN_PASSWORD = oldPassword;
    if (oldSecret === undefined) delete process.env.AccessTokenSecret; else process.env.AccessTokenSecret = oldSecret;
    if (oldAutofill === undefined) delete process.env.ENABLE_ADMIN_AUTOFILL; else process.env.ENABLE_ADMIN_AUTOFILL = oldAutofill;
    if (oldDemos === undefined) delete process.env.ENABLE_DEMO_ACCOUNTS; else process.env.ENABLE_DEMO_ACCOUNTS = oldDemos;
    if (oldNodeEnv === undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV = oldNodeEnv;
    await new Promise((resolve) => server.close(resolve));
  }
});
